### ISSUE TITLE
最新代码在双开微信时第一次启动报错

### ISSUE THREAD

**Issue by piersguo** [asLody/VirtualApp#100]
我测试用的小米4，Android4.4手机，抓了其停止运行错误log如下:
09-09 09:21:30.563 E/AndroidRuntime(29497): FATAL EXCEPTION: main
09-09 09:21:30.563 E/AndroidRuntime(29497): Process: io.virtualapp:x, PID: 29497
09-09 09:21:30.563 E/AndroidRuntime(29497): java.util.ConcurrentModificationException
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at com.lody.virtual.service.am.ActivityStack$1.handleMessage(ActivityStack.java:51)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at android.os.Looper.loop(Looper.java:136)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
09-09 09:21:30.563 E/AndroidRuntime(29497): 	at dalvik.system.NativeStart.main(Native Method)

我看了代码应该是在for (ActivityRecord r : task.activities) 迭代时候，内部r.process.client.finishActivity 调用可能对ActivityRecord 有修改，导致了这个错误。

**Comment by winter-zhang** [comment]
改成iteration进行迭代就可以了
