### ISSUE TITLE
微信在后台时，无法接收消息

### ISSUE THREAD

**Issue by snaileo** [asLody/VirtualApp#103]
事实上，应该是无法显示新信息的通知。

android 5.1，2016/09/11的版本

**Comment by tjt852** [comment]
+1，，，，，我也是无法接受消息，android6.0.1 三星s6

**Comment by cddjr** [comment]
这个bug经过我的测试，根源在于VA的广播组件实现上还有点bug，需要做一些修复工作~

**Comment by tjt852** [comment]
谢谢你的回复，如果修复好了给我个回复，我在看你的源码，，，里面的很多东西对我很有帮助

2016-11-10 16:09 GMT+08:00 大侠 <notifications@github.com>:
