### ISSUE TITLE
抛出一个话题：在virtualapp中加载virtualapp....

### ISSUE THREAD

**Issue by tianfengjingjing** [asLody/VirtualApp#105]
目前已知的双开比较好的是LBE平行空间，目前尝试在LBE中开VirutalApp，然后再加载LBE，，各种嵌套之后，界面卡死。
是不是可以分析下，各种hook之间谁胜谁负，如何保证hook是透明，安全的

**Comment by asLody** [comment]
目前已支持在VA中直接运行DroidPlugin.
