### ISSUE TITLE
请教作者jni目录下的代码和项目引入的问题

### ISSUE THREAD

**Issue by wangli0** [asLody/VirtualApp#110]
作者你好，初次接触你这项目，请教一下 jni目录下面的c代码 需要自己编译后引入Android studio吗，为什么不是.so文件呢。还有之前你提到的android.jar，上次您的版本还存在，这次没有了这个文件，不知道怎么导入项目呢

**Comment by Oueer** [comment]
你说的jni我不太清楚，但是那个android.jar作者在某个版本就已经移除了，你直接导入项目就可以了，现在可以直接用sdk中原有的android.jar，不用替换哩

**Comment by wangli0** [comment]
这个项目支持启动带有 so文件的插件app吗？ 刚试了下360的是不支持的
