### ISSUE TITLE
VirtualCore 中isAppRunning方法判断错误

### ISSUE THREAD

**Issue by sunpengshuai** [asLody/VirtualApp#128]
我用VA打开插件程序，然后手动点击back键，关闭程序。
在宿主中用isAppRunning进行判断，发现返回结果仍然是true

**Comment by sunpengshuai** [comment]
插件程序的最后一个Activity关闭的时候，是不是当前程序进程也应该关闭呢？

**Comment by imilk** [comment]
除了Activity还有Service呢，谁说页面关闭了，进程就该销毁呢。

**Comment by sunpengshuai** [comment]
哦 抱歉。插件程序里面没有service，只是一个简单的AC

**Comment by imilk** [comment]
这根只有Activity没啥关系，系统进程是有缓存的，不是页面全部弹栈就会杀死进程的。

**Comment by sunpengshuai** [comment]
嗯 你说的这个，有些道理。我是想通过这个方法判断，当前的插件进程是不是正在前台显示。即是否界面显示中，看来不能调用这个方法了。我再想想其他办法
