### ISSUE TITLE
Genymotion Android5.0以及以上系统版本中arm支持有问题

### ISSUE THREAD

**Issue by sunpengshuai** [asLody/VirtualApp#136]
使用Genymontion虚拟机，首先说明下，Genymotion官方只支持X86体系架构。从网上找到Genymotion_ARM_Translation_5.1_Lollipop,装进虚拟机后。重新启动虚拟机。此时Genymotion可以直接装arm体系架构的apk。但是装上VA后，直接通过VA双开手机中已经存在的Arm架构的apk，打开出现问题。加载so，加载不上。直接崩溃。

**Comment by sunpengshuai** [comment]
在转化以后的虚拟机中，是可以正常打开使用仅支持arm体系apk的。

**Comment by 247321453** [comment]
这样有何意义？
