### ISSUE TITLE
微信在群聊界面返回时发生卡死问题

### ISSUE THREAD

**Issue by crownbox** [asLody/VirtualApp#139]
在华为Mate7上用virtualApp打开微信，点击通讯录-》群聊-》随便进个群，然后点击返回键，这时候微信微信会有几率黑屏，卡住。
下面是logcat:
io.virtualapp:p0 D/AndroidRuntime: Shutting down VM
io.virtualapp:p0 W/System.err: java.lang.RuntimeException: Unable to destroy activity {com.tencent.mm/com.tencent.mm.ui.LauncherUI}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getShortClassName()' on a null object reference
io.virtualapp:p0 W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3975)
io.virtualapp:p0 W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3993)
io.virtualapp:p0 W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:163)
io.virtualapp:p0 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1429)
io.virtualapp:p0 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
io.virtualapp:p0 W/System.err:     at android.os.Looper.loop(Looper.java:137)
io.virtualapp:p0 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5595)
io.virtualapp:p0 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
io.virtualapp:p0 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
io.virtualapp:p0 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
io.virtualapp:p0 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
io.virtualapp:p0 W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getShortClassName()' on a null object reference
io.virtualapp:p0 W/System.err:     at com.tencent.mm.sdk.platformtools.be$a.toString(SourceFile:2163)
io.virtualapp:p0 W/System.err:     at java.util.Formatter.transform(Formatter.java:1421)
io.virtualapp:p0 W/System.err:     at java.util.Formatter.doFormat(Formatter.java:1081)
io.virtualapp:p0 W/System.err:     at java.util.Formatter.format(Formatter.java:1042)
io.virtualapp:p0 W/System.err:     at java.util.Formatter.format(Formatter.java:1011)
io.virtualapp:p0 W/System.err:     at java.lang.String.format(String.java:1803)
io.virtualapp:p0 W/System.err:     at java.lang.String.format(String.java:1777)
io.virtualapp:p0 W/System.err:     at com.tencent.mm.sdk.platformtools.v.i(SourceFile:262)
io.virtualapp:p0 W/System.err:     at com.tencent.mm.ui.chatting.ChattingUI$a.onDestroy(SourceFile:2774)
io.virtualapp:p0 W/System.err:     at android.support.v4.app.l.a(SourceFile:1196)
io.virtualapp:p0 W/System.err:     at android.support.v4.app.l.a(SourceFile:1252)
io.virtualapp:p0 W/System.err:     at android.support.v4.app.l.G(SourceFile:1234)
io.virtualapp:p0 W/System.err:     at android.support.v4.app.l.dispatchDestroy(SourceFile:2083)
io.virtualapp:p0 W/System.err:     at android.support.v4.app.FragmentActivity.onDestroy(SourceFile:369)
io.virtualapp:p0 W/System.err:     at android.support.v7.app.AppCompatActivity.onDestroy(SourceFile:193)
io.virtualapp:p0 W/System.err:     at com.tencent.mm.ui.MMFragmentActivity.onDestroy(SourceFile:97)
io.virtualapp:p0 W/System.err:     at com.tencent.mm.ui.LauncherUI.onDestroy(SourceFile:1574)
io.virtualapp:p0 W/System.err:     at android.app.Activity.performDestroy(Activity.java:6301)
io.virtualapp:p0 W/System.err:     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1144)
io.virtualapp:p0 W/System.err:     at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnDestroy(InstrumentationDelegate.java:255)
io.virtualapp:p0 W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3962)
io.virtualapp:p0 W/System.err: 	... 10 more

**Comment by cddjr** [comment]
三星S7 edge 6.0重现了。。。

**Comment by cddjr** [comment]
我的临时修复方案是修改 AppTaskInfo getAppTaskInfo()方法，你可以试试看，我这边已经不会黑屏了
```
-        ComponentName top = len > 0 ? activities.get(len - 1).component : null;
+        ComponentName top = len > 0 ? activities.get(len - 1).component : taskRoot.getComponent();
```

**Comment by crownbox** [comment]
刚才你的方法你也发现问题了吧，返回之后再返回就又进入群聊界面了。我看下了双开大师的解决方法，它好像是在按返回的时候先关闭了群聊界面，然后又重新打开了群聊界面，再次按返回的时候就正常退出了。
