### ISSUE TITLE
BUG反馈: VirtualCore.getCore().installApp 不能安装新版本

### ISSUE THREAD

**Issue by 11245702** [asLody/VirtualApp#14]
测试对象：直接存储在/sdcard/test.apk  的文件
情况：能检测到新版本，但每次安装后，还是老版本。

**Comment by 11245702** [comment]
使用示例：VirtualCore.getCore().installApp(apk_cocplugin, InstallStrategy.COMPARE_VERSION);

**Comment by asLody** [comment]
Fixed.
