### ISSUE TITLE
通过System.load方式加载so库的app无法正常运行

### ISSUE THREAD

**Issue by cloud20161002** [asLody/VirtualApp#155]
现象：如标题，可能是dlopen的重定向有问题；比如那些在360手机助手上经过加固的app
android版本：7.0

**Comment by cddjr** [comment]
va默认没开IO重定向，我本地是开了这个功能的，暂时没有重现这类问题。 或许你可以提供一个具体apk，我试试看。

**Comment by cloud20161002** [comment]
可以看看这个应用：http://android.myapp.com/myapp/detail.htm?apkName=com.android.icredit

**Comment by cddjr** [comment]
恩，没有问题，使用正常。  那应该就是打开IO重定向即可解决了

**Comment by cloud20161002** [comment]
我已经打开了io重定向，但还是不能启动那个应用，是我打开的方式不对么？我是如下做的：
**在VClientImpl的bindApplication方法里，通过调用IOHook.redirect(origPath, newPath)，origPath："/data/data/pkgname"
newPath : "/data/data/hostpackage/data/user/0/pkgname"**

请帮忙看看，多谢
