### ISSUE TITLE
反馈崩溃BUG:  关于 Hook_GetTasks.java  

### ISSUE THREAD

**Issue by 11245702** [asLody/VirtualApp#16]
日志如下：
W/System.err(19742):    at android.os.BinderProxy.transact(Native Method)
W/System.err(19742):    at com.lody.virtual.service.IActivityManager$Stub$Proxy.getTaskInfo(IActivityManager.java:226)
W/System.err(19742):    at com.lody.virtual.client.local.LocalActivityManager.getTaskInfo(LocalActivityManager.java:102)
W/System.err(19742):    at com.lody.virtual.client.hook.patchs.am.Hook_GetTasks.onHook(Hook_GetTasks.java:41)
W/System.err(19742):    at com.lody.virtual.client.hook.base.HookObject$HookHandler.invoke(HookObject.java:146)
W/System.err(19742):    at $Proxy0.getTasks(Native Method)
W/System.err(19742):    at android.app.ActivityManager.getRunningTasks(ActivityManager.java:769)
W/System.err(19742):    at android.app.ActivityManager.getRunningTasks(ActivityManager.java:805)
W/System.err(19742):    at cn.uc.gamesdk.lib.util.k.i(Unknown Source)
W/System.err(19742):    at cn.uc.gamesdk.lib.util.k.h(Unknown Source)
W/System.err(19742):    at cn.uc.gamesdk.core.t.b.e(Unknown Source)
W/System.err(19742):    at cn.uc.gamesdk.core.t.b.a(Unknown Source)
W/System.err(19742):    at cn.uc.gamesdk.core.t.b$2.run(Unknown Source)
W/System.err(19742):    at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(19742):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(19742):    at android.os.Looper.loop(Looper.java:136)
W/System.err(19742):    at android.os.HandlerThread.run(HandlerThread.java:61)
I/Process (19742): Sending signal. PID: 19742 SIG: 9

**Comment by asLody** [comment]
Fixed.
