### ISSUE TITLE
请教如何hook住Activity里的函数

### ISSUE THREAD

**Issue by casazaft** [asLody/VirtualApp#163]
看了一下代码，发现这个框架里能够patch的都是一些单例对象，不知道对于动态创建的对象，比如activity，如果我需要在onActivityResult这样的函数前后做hook，要如何操作？能否给个思路？谢谢！

**Comment by ouer1994** [comment]
hook的最佳选择对象就是单例的，要不你也不好hook住啊，对于方法的hook主要是用反射和代理，去百度查查

**Comment by ouer1994** [comment]
@casazaft hook的最佳选择对象就是单例的，要不你也不好hook住啊，对于方法的hook主要是用反射和代理，去百度查查

**Comment by asLody** [comment]
参考io.virtualapp.MyComponentDelegate。
