### ISSUE TITLE
崩溃BUG: Hook_GetRunningAppProcesses

### ISSUE THREAD

**Issue by 11245702** [asLody/VirtualApp#17]
日志：
W/System.err(15415): android.os.DeadObjectException
W/System.err(15415): android.os.DeadObjectException
W/System.err(15415):    at android.os.BinderProxy.transact(Native Method)
W/System.err(15415):    at com.lody.virtual.service.IProcessManager$Stub$Proxy.getAppProcessName(IProcessManager.java:343)
W/System.err(15415):    at com.lody.virtual.client.local.LocalProcessManager.getAppProcessName(LocalProcessManager.java:143)
W/System.err(15415):    at com.lody.virtual.client.hook.patchs.am.Hook_GetRunningAppProcesses.onHook(Hook_GetRunningAppProcesses.java:43)
W/System.err(15415):    at com.lody.virtual.client.hook.base.HookObject$HookHandler.invoke(HookObject.java:146)
W/System.err(15415):    at $Proxy0.getRunningAppProcesses(Native Method)
W/System.err(15415):    at android.app.ActivityManager.getRunningAppProcesses(ActivityManager.java:1872)
W/System.err(15415):    at cn.uc.gamesdk.core.t.b$2.run(Unknown Source)
W/System.err(15415):    at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(15415):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(15415):    at android.os.Looper.loop(Looper.java:136)
W/System.err(15415):    at android.os.HandlerThread.run(HandlerThread.java:61)
I/Process (15415): Sending signal. PID: 15415 SIG: 9

**Comment by asLody** [comment]
Fixed.
