### ISSUE TITLE
android 6.0以上的录音和拍照权限问题

### ISSUE THREAD

**Issue by casazaft** [asLody/VirtualApp#175]
6.0以上应用程序需要做动态授权才能拿到录音等功能的权限，请问这个要怎么支持才行？

**Comment by casazaft** [comment]
我试过在app的MainActivity里面去requestPermissions，或者在stubActivity里面拿权限，但似乎没有起效果。被虚拟化的程序仍然拿不到权限。

**Comment by sudami** [comment]
不需要动态授权,在XML里面写好所有的权限,设置为兼容23版本即可.
如果有权限问题,可能是Meida层代码处理有问题, 比如meida --> query,insert

**Comment by asLody** [comment]
这是将来会解决的问题，需要在Native层做处理。

**Comment by codehz** [comment]
7.1.1 测试是可以的，动态权限正常授予，应用未闪退（我测试的是[氢相机](https://www.androidfilehost.com/?w=files&flid=121579)），不知道是不是已经修复了

**Comment by loveAndroid** [comment]
在魅族手机上也遇到了这个问题 。 MEIZU PRO5 3G 版本的 安卓6.0 flyme 6.0.2.0A 微信打开扫一扫，提示无摄像头权限。
