### ISSUE TITLE
在运行经过360加固的应用的时候，代码Application app = LoadedApk.makeApplication.call(data.info, false, null);会报空指针的错误。

### ISSUE THREAD

**Issue by hanyuejian** [asLody/VirtualApp#184]

**Comment by sudami** [comment]
solution: 
native hook "dlopen", redirect path

reason:
360加固会释放并加载jiagu.so文件,少了以上hook,就会漏掉这个重定向,导致打不开对应的jiagu.so,于是GG

**Comment by hanyuejian** [comment]
恩，的确是这个dlopen函数发现了找不到so文件的错误

**Comment by asLody** [comment]
现已支持360加固。
