### ISSUE TITLE
双开需要使用相机的软件 在6.0以下好像都有问题

### ISSUE THREAD

**Issue by youtouAshu** [asLody/VirtualApp#187]
我目前双开的几款有用到摄像头的软件在几台5.0.1和5.1.1的测试机上都无法正常使用，个别还会出现闪退现象， 6.0上没有发现这个问题

**Comment by sudami** [comment]
@youtouAshu 
solution:
native hook some funcionts below:

**MediaRecorder!native_setup
Camera!native_setup
AudioRecord!native_check_permission**

relapce sandbox pkg name with your host pkg name

**Comment by youtouAshu** [comment]
@sudami 
谢谢 这么快就回复了 我近几天看了源码后 觉得应该也是Uid,PackageName在appops的校验上没通过，无奈基础不是很扎实 你现在的意思应该是针对这几个native的方法 hook后替换包名是吧 ，不知道 这个项目本身有没有其他 hook native 方法的例子 让我做个参考后 进行尝试

**Comment by youtouAshu** [comment]
@sudami  谢谢 我已经解决了 撒花

**Comment by asLody** [comment]
提个PR吧
