### ISSUE TITLE
Activity启动时收不到动态注册的广播

### ISSUE THREAD

**Issue by cocosjiang** [asLody/VirtualApp#189]
public class MyNetChangTestActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_layout);

        IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(ConnectivityManager.CONNECTIVITY_ACTION);
        this.registerReceiver(mReceiver, intentFilter);

    }
    private BroadcastReceiver mReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
            if (action.equals(ConnectivityManager.CONNECTIVITY_ACTION)) {
                NetworkInfo info = intent.getParcelableExtra(ConnectivityManager.EXTRA_NETWORK_INFO);
                Toast.makeText(MyNetChangTestActivity.this,"receive broadcast:"+info.getExtraInfo(),Toast.LENGTH_LONG).show();
            }
        }
    };
}
这个Activity启动后应该到一个网络状态Change的广播，但是作为双开运行在Virtual App上收不到广播。

**Comment by sewasewa777** [comment]
#189
