### ISSUE TITLE
处在virtualapp中的app如何检测自己处于虚拟化

### ISSUE THREAD

**Issue by casazaft** [asLody/VirtualApp#194]
如果想为正常运行和virtual app运行做区别，请问如何能检测？

**Comment by asLody** [comment]
让运行在VA的app无法感知自己处于虚拟化，才是VA的目标。

**Comment by casazaft** [comment]
目前来看，如果在app里面throw一个异常，自己再捕获，是可以看到堆栈信息里面virtual app的痕迹

**Comment by casazaft** [comment]
正在研究一下如何hook掉exception handler

**Comment by sewasewa777** [comment]
#162
