### ISSUE TITLE
android 7.x (由默认启用的严格模式限制)禁止intent传递file协议的data

### ISSUE THREAD

**Issue by codehz** [asLody/VirtualApp#197]
如果targetApi为N，则会报错：android.os.FileUriExposedException
我觉得这是可以通过修改IntentFilter解决的...先发个issue，我试试能不能自己解决

**Comment by asLody** [comment]
能否提供样本？

**Comment by codehz** [comment]
样本：酷安
行为：在容器中尝试安装软件
系统版本：7.1.1
我指的targetApi是指host应用的targetApi
