### ISSUE TITLE
OPPO A31   4.4.4系统   获取sd卡私有目录失败

### ISSUE THREAD

**Issue by cocosjiang** [asLody/VirtualApp#207]
File externalCacheDir = context.getExternalCacheDir();
或context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);
![2017-02-09 6 30 30](https://cloud.githubusercontent.com/assets/7485297/22779474/e982cec0-eef5-11e6-86f7-557c32887918.png)

**Comment by asLody** [comment]
一个条件导致的异常 😂
