### ISSUE TITLE
扩展通知高度不正确

### ISSUE THREAD

**Issue by codehz** [asLody/VirtualApp#209]
约为原高度的2倍。。（似乎是系统允许的最大高度）
系统是7.1.1 应该和ROM关系不大。。

**Comment by codehz** [comment]
关键调试输出：
```
I/RemoteViewsUtils: notification:systemId=false,max=1036/248, szie=1036/248
I/RemoteViewsUtils: notification:systemId=false,max=1036/767, szie=1036/767
```
注：两条连续

**Comment by asLody** [comment]
@247321453

**Comment by codehz** [comment]
```Java
mCache.measure(View.MeasureSpec.makeMeasureSpec(width, mode), View.MeasureSpec.makeMeasureSpec(height, mode));
mCache.layout(0, 0, width, mCache.getMeasuredHeight());
```
似乎把关键的代码改成这样就可以了（RemoteViewsUtils：`public View createView(final Context context, RemoteViews remoteViews, boolean isBig, boolean systemId)`函数的倒数第3行），由于不熟悉这段源代码，还是你来看看吧 @247321453

**Comment by codehz** [comment]
@247321453 sSystemLayoutResIds在7.1下获取到的居然是空的。。。准确的说，整个R_Hide的反射都是空的。。。

**Comment by 247321453** [comment]
我的github的va在5.0采用了替换applicationinfo的方法，通知栏不再是画的了，而是一模一样。（目前有2个问题：1.va的插件apk开放读的权限，2.自定义通知栏的背景色总是白的）

**Comment by codehz** [comment]
@247321453 看到了，看起来那个版本的代码好理解多了。。。。

**Comment by 247321453** [comment]
@codehz 我的代码更新了，4.x的系统样式和5.0以上的通知栏都是和系统一样，就4.x的自定义布局可能有点视觉差异。至于啥时候合并，需要再看看
