### ISSUE TITLE
发送广播 intent里的数据丢失

### ISSUE THREAD

**Issue by cocosjiang** [asLody/VirtualApp#213]
发送：  Intent intent = new Intent("com.test");  Bundle bundle = new Bundle();
                bundle.putString("test","bundle is empty");
              intent.putExtra("broadCast",bundle);
            sendBroadcast(intent);
收到： Bundle bundle = intent.getBundleExtra("broadCast");  此时 bundle为空

**Comment by 247321453** [comment]
已经知道原因，正在修

**Comment by asLody** [comment]
Fixed
