### ISSUE TITLE
使用了NeoX的网易系游戏都会在chdir()后闪退

### ISSUE THREAD

**Issue by siweg** [asLody/VirtualApp#216]
使用了NeoX的网易系游戏都会在chdir()后闪退, 比如阴阳师，镇魔曲。

比如镇魔曲在小米5, Android 6.0.1上，logcat中打印
E/VA-Native: chdir, orig /storage/emulated/0/Android/data/com.netease.zmq/files/Netease/zmq
E/VA-Native: chdir, new /storage/emulated/0/Android/data/com.netease.zmq/files/Netease/zmq

后就会异常，触发google-breakpad.

**Comment by asLody** [comment]
Fixed :) 😊
