### ISSUE TITLE
创建虚拟应用桌面图标，重启一次手机后图标名称变为与Host名称一样

### ISSUE THREAD

**Issue by liangliangan** [asLody/VirtualApp#232]
创建的虚拟应用桌面图标在重启一次手机后名称会变为与Host一样，测试了手中的几部国产机都是如此。

**Comment by codehz** [comment]
这个明显是桌面bug，并非软件能解决的

**Comment by liangliangan** [comment]
@codehz 确实如你所说，这是手机桌面的bug。我换了第三部手机测试是正常的。
