### ISSUE TITLE
打开梆梆加固的某应用出现crash

### ISSUE THREAD

**Issue by rrrfff** [asLody/VirtualApp#237]
下面是crash细节, 未深究, 不知是virtualapp本身缺陷还是该加固反virtual
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/dior/dior:4.4.4/KTU84P/7.1.20:user/release-keys'
Revision: '0'
pid: 23316, tid: 23316, name: gbanjie.android  >>> com.tongbanjie.android <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 4010f4ec
    r0 5fa97648  r1 4010f4f0  r2 5fa6a46d  r3 5f93b4f5
    r4 00000001  r5 4010f4e8  r6 00006068  r7 4010f4e8
    r8 5fa97648  r9 5fa92e18  sl beb2a68c  fp 0000aaab
    ip 5b144001  sp beb2a598  lr 5fa6f913  pc 5fa6ed8e  cpsr 80070030
    d0  0000000000000000  d1  0000000000000000
    d2  0000000000000000  d3  0000000000000000
    d4  577ffac0577ffa88  d5  577ffb30577ffaf8
    d6  577ffba0577ffb68  d7  3f800000577ffbd8
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 632f65686361632e  d17 642e73657373616c
    d18 616c617574726976  d19 75747269762f7070
    d20 2f617461642f6c61  d21 632f302f72657375
    d22 62676e6f742e6d6f  d23 6e612e65696a6e61
    d24 3fc74721cad6b0ed  d25 3fc2f112df3e5244
    d26 40026bb1bbb55516  d27 4000000000000000
    d28 40008df2d49d41f1  d29 3fb0f4a31edab38b
    d30 3ff0000000000000  d31 3f4de16b9c24a98f
    scr 60000010

backtrace:
    #00  pc 0001ed8e  /data/data/io.virtualapp/virtual/data/app/com.tongbanjie.android/lib/libDexHelper.so
    #01  pc 0001f90f  /data/data/io.virtualapp/virtual/data/app/com.tongbanjie.android/lib/libDexHelper.so (pC5729AA463A28F2BB0D2F632BDC33FC1+74)
    #02  pc 0001c5fd  /data/data/io.virtualapp/virtual/data/app/com.tongbanjie.android/lib/libDexHelper.so (pA0C66AAC4D0944A9CDC769B10863861E+1920)
    #03  pc 00011b67  /data/data/io.virtualapp/virtual/data/app/com.tongbanjie.android/lib/libDexHelper.so (JNI_OnLoad+11878)
    #04  pc 00052eb1  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+468)
    #05  pc 000156c9  /system/lib/libdvm.so

code around pc:
    5fa6ed6c 9804e150 60032300 9810e151 4288499f  
    5fa6ed7c 2008bf14 e76e2001 f1079a08 98040108  
    5fa6ed8c 607a9b11 60032200 f7eb4638 e13eeee4  
    5fa6ed9c 0288ea4f 4413ab12 3208443a f853920b  
    5fa6edac f04f3c08 f04f0a02 f0130c01 9109010f  
    5fa6edbc f04fbf14 f04f0b00 f8cd0b01 f8ddb028  
    5fa6edcc f3c3b014 f3c36140 90023003 4280f10b  
    5fa6eddc f1ba3a03 d8fc0f07 f00ae8df 385c4452  
    5fa6edec 140a0467 f04f980a f3600b01 e04c4313  
    5fa6edfc b01cf8dd 0f00f1bb f04fbf0c f04f0a07  
    5fa6ee0c e7e60a04 4b03f3c3 0a02ebc4 3b0bea4f  
    5fa6ee1c 0a8aea4f 4b65f04b 0f00f1ba f1cabfb8  
    5fa6ee2c f44b0a00 ea4b0b1f f8dd0a0a f845b01c  
    5fa6ee3c eb05a024 34020a84 3004f8ca 0f00f1bb  
    5fa6ee4c f04fbf0c f04f0a03 e7c20a01 980b9906  
    5fa6ee5c b014f8dd 60083904 3bfff10b f8cd9106  

code around lr:
    5fa6f8f0 4648e028 f7eb4651 2800e85c bf0c4605  
    5fa6f900 24042401 4628e7ec 46424639 f7ff2401  
    5fa6f910 e7e5f987 f406fb0b 3d012303 46424639  
    5fa6f920 0c644628 6414fb03 fb7af7ff 0403f1c4  
    5fa6f930 d1d52c05 07ece006 2400bf46 36d8f646  
    5fa6f940 e7cd2402 e8bdb003 b1388ff0 0f01f010  
    5fa6f950 3801d002 bb64f7ff b962f7ff e92d4770  
    5fa6f960 b0894ff0 46072300 200c9307 f6439b07  
    5fa6f970 910439d4 38019205 d81a280c f000e8df  
    5fa6f980 0733d0df 1f09e10e 13c7dbba 1c7800b5  
    5fa6f990 2c03e0d8 2008bf94 e7ec2000 73daeb0a  
    5fa6f9a0 0463eb04 f017e0c9 bf140f01 2001200d  
    5fa6f9b0 f1b8e7e1 bf140f00 20042006 1930e7db  
    5fa6f9c0 f8aef7ff f8364682 f4000014 f5b34370  
    5fa6f9d0 f0404f50 f40080ae f5b06060 bf146f60  
    5fa6f9e0 20022009 eb06e7c7 f8360044 88421014

**Comment by rrrfff** [comment]
另外该应用使用360的双开助手能正常打开

**Comment by zhangyiran** [comment]
va支持梆梆加固吗
