### ISSUE TITLE
failed to build. me.tatarka.retrolambda not found

### ISSUE THREAD

**Issue by bon-ami** [asLody/VirtualApp#247]
gradle reports "plugin with id 'me.tatarka.retrolambda' not found."

**Comment by 247321453** [comment]
请自备梯子

**Comment by bon-ami** [comment]
@247321453 配置中，写代理，然后验证，能访问http://retrolambda.tatarka.me
Plugin with id 'me.tatarka.retrolambda' not found

**Comment by 247321453** [comment]
你的项目是新建的吧，或者你改了project的东西

**Comment by 247321453** [comment]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
   }
}

**Comment by bon-ami** [comment]
@247321453 我就是VA的代码啊，app/build.gradle第二行出错
`apply plugin: 'com.android.application'`
`apply plugin: 'me.tatarka.retrolambda'`

**Comment by 247321453** [comment]
你这个出错的原因：1.project的build.gradle没引用classpath 'me.tatarka:gradle-retrolambda:3.2.5'；2.你的网络有问题/或者你的gradle是离线模式
