### ISSUE TITLE
what's text '[Admin]'  in recent activity

### ISSUE THREAD

**Issue by thinkinfish** [asLody/VirtualApp#272]
like this,
![https://raw.githubusercontent.com/thinkinfish/Hello/master/123.png](https://raw.githubusercontent.com/thinkinfish/Hello/master/123.png)
how to remove [Admin]

**Comment by codehz** [comment]
https://github.com/asLody/VirtualApp/blob/master/VirtualApp/app/src/main/java/io/virtualapp/delegate/MyTaskDescriptionDelegate.java
