### ISSUE TITLE
进程名称问题

### ISSUE THREAD

**Issue by thinkinfish** [asLody/VirtualApp#274]
![Uploading 123.png…](https://raw.githubusercontent.com/thinkinfish/Hello/master/123.png)

allprocess 是一个demo，一个service 还有一个activity
myapplication 是VirtualApp，加载了allprocess 和qq阅读
出现这种情况是怎么回事，应该都是myapplication:p啊，为啥还有com.example.allprocess？

**Comment by asLody** [comment]
VirtualRuntime里通过Process.setArg0伪装进程名。

**Comment by thinkinfish** [comment]
还有一个不太理解
![Uploading 123.png…](https://raw.githubusercontent.com/thinkinfish/Hello/master/1234.png)
![Uploading 123.png…](https://raw.githubusercontent.com/thinkinfish/Hello/master/qq1.png)

Process.setArg0设置了正确的名字，ps也可以看到，studio中显示的怎么还是p0
