### ISSUE TITLE
关于移动mm平台游戏

### ISSUE THREAD

**Issue by androiddy** [asLody/VirtualApp#275]
移动mm平台游戏无法使用va来启动
http://mm.10086.cn/android/game/dzmx?pay=1

04-08 20:57:29.869 15306-15306/com.hookallgame:p0 D/VA-Native: do_dlopen : /system/lib/libc.so, return : 0xb6f9bd04.
04-08 20:57:29.871 15306-15306/com.hookallgame:p0 A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xb6d431c0 in tid 15306 (ong.jijiehao233)

**Comment by asLody** [comment]
已支持。
