### ISSUE TITLE
双开QQ, 发现 ->看点 功能不能用

### ISSUE THREAD

**Issue by xmlqq** [asLody/VirtualApp#283]
双开QQ, 发现 ->看点 功能不能用

**Comment by xmlqq** [comment]
com.tencent.mobileqq:readinjoy E/art: The String#value field is not present on Android versions >= 6.0
com.tencent.mobileqq:readinjoy W/System.err: java.lang.NoSuchFieldException: No field value in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)

**Comment by asLody** [comment]
没必要标注是华为荣耀8，这样会形成误导，这是在所有设备上都可以复现的bug。

**Comment by asLody** [comment]
没意义的log就不要发了，截的log都是正常输出。

**Comment by xmlqq** [comment]
QQ->发现->看点， 这个功能不能用。

**Comment by asLody** [comment]
目前版本已正常。
