### ISSUE TITLE
为什么启动微信或者QQ的时候有个黑屏呢？

### ISSUE THREAD

**Issue by xmlqq** [asLody/VirtualApp#286]
为什么启动微信或者QQ的时候有个黑屏呢？

**Comment by xmlqq** [comment]
经测试，在VClientImpl类里，bindApplicationNoCheck函数下：             
context = createPackageContext(pkgName);
这个方法阻塞了进程，耗时4-5秒。 

我的修改方案是， 在Application下把packageContext先预加载出来，然后在这里直接取，不用每次都创建。

这个是一个笨办法。 就不PR了。

另外比较耗时的是startIOUniformer方法。  
每次都会被重复执行， 如果在一个Application或进程里面只执行一次，应该就好了。

请知悉。

**Comment by 247321453** [comment]
混淆问题吧
-keepattributes *Annotation*,InnerClasses
