### ISSUE TITLE
用了这个微信被封了，请问被封的原因有可能有哪些？

### ISSUE THREAD

**Issue by hetykai** [asLody/VirtualApp#295]
rt

**Comment by triwater** [comment]
没逆过微信源码，我猜是微信查看了自己的调用栈，看到调用路径中有VA的代码

**Comment by asLody** [comment]
原因是你在一台设备上同时登陆了多个微信，你需要Hack设备IMEI，MAC地址，型号等信息以后才可以这样做，否则就会被封号。
