### ISSUE TITLE
Asset path /mnt/asec/com.tencent.mobileqq-1/base.apk is neither a directory nor file (type=1).

### ISSUE THREAD

**Issue by htzz271** [asLody/VirtualApp#320]
Asset path /mnt/asec/com.tencent.mobileqq-1/base.apk is neither a directory nor file (type=1).
PackageManager: Failure retrieving resources for com.tencent.mobileqq
手机上的qq升级后，启动va会出现这个问题，va上显示的图标错误，还有启动不了

**Comment by perfactwork** [comment]
这个是因为升级后apk的路径变了
