### ISSUE TITLE
 android.os.DeadObjectException

### ISSUE THREAD

**Issue by rrrfff** [asLody/VirtualApp#321]
--------- beginning of main
W/System.err( 4553): android.os.DeadObjectException
W/System.err( 4553):    at android.os.BinderProxy.transactNative(Native Method)
W/System.err( 4553):    at android.os.BinderProxy.transact(Binder.java:496)
W/System.err( 4553):    at com.lody.virtual.server.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:860)
W/System.err( 4553):    at com.lody.virtual.client.ipc.VPackageManager.queryIntentActivities(VPackageManager.java:166)
W/System.err( 4553):    at com.lody.virtual.client.core.VirtualCore.getLaunchIntent(VirtualCore.java:371)
W/System.err( 4553):    at io.virtualapp.home.LoadingActivity.launch(LoadingActivity.java:35)
W/System.err( 4553):    at io.virtualapp.home.HomePresenterImpl.launchApp(HomePresenterImpl.java:55)
W/System.err( 4553):    at io.virtualapp.home.HomeActivity.lambda$initLaunchpad$0(HomeActivity.java:109)
W/System.err( 4553):    at io.virtualapp.home.HomeActivity$$Lambda$1.onAppClick(Unknown Source)
W/System.err( 4553):    at io.virtualapp.home.adapters.LaunchpadAdapter.lambda$onBindViewHolder$0(LaunchpadAdapter.java:69)
W/System.err( 4553):    at io.virtualapp.home.adapters.LaunchpadAdapter$$Lambda$1.onClick(Unknown Source)
W/System.err( 4553):    at android.view.View.performClick(View.java:4756)
W/System.err( 4553):    at android.view.View$PerformClick.run(View.java:19749)
W/System.err( 4553):    at android.os.Handler.handleCallback(Handler.java:739)
W/AudioTrack( 1787): AUDIO_OUTPUT_FLAG_FAST denied by client
W/System.err( 4553):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 4553):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 4553):    at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 4553):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4553):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 4553):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 4553):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/System.err( 4553): com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException
W/System.err( 4553):    at com.lody.virtual.client.env.VirtualRuntime.crash(VirtualRuntime.java:61)
W/System.err( 4553):    at com.lody.virtual.client.ipc.VPackageManager.queryIntentActivities(VPackageManager.java:168)
W/System.err( 4553):    at com.lody.virtual.client.core.VirtualCore.getLaunchIntent(VirtualCore.java:371)
W/System.err( 4553):    at io.virtualapp.home.LoadingActivity.launch(LoadingActivity.java:35)
W/System.err( 4553):    at io.virtualapp.home.HomePresenterImpl.launchApp(HomePresenterImpl.java:55)
W/System.err( 4553):    at io.virtualapp.home.HomeActivity.lambda$initLaunchpad$0(HomeActivity.java:109)
W/System.err( 4553):    at io.virtualapp.home.HomeActivity$$Lambda$1.onAppClick(Unknown Source)
W/System.err( 4553):    at io.virtualapp.home.adapters.LaunchpadAdapter.lambda$onBindViewHolder$0(LaunchpadAdapter.java:69)
W/System.err( 4553):    at io.virtualapp.home.adapters.LaunchpadAdapter$$Lambda$1.onClick(Unknown Source)
W/System.err( 4553):    at android.view.View.performClick(View.java:4756)
W/System.err( 4553):    at android.view.View$PerformClick.run(View.java:19749)
W/System.err( 4553):    at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 4553):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 4553):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 4553):    at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 4553):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4553):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 4553):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 4553):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/System.err( 4553): Caused by: android.os.DeadObjectException
W/System.err( 4553):    at android.os.BinderProxy.transactNative(Native Method)
W/System.err( 4553):    at android.os.BinderProxy.transact(Binder.java:496)
W/System.err( 4553):    at com.lody.virtual.server.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:860)
W/System.err( 4553):    at com.lody.virtual.client.ipc.VPackageManager.queryIntentActivities(VPackageManager.java:166)
W/System.err( 4553):    ... 17 more

**Comment by asLody** [comment]
You must reo

**Comment by xinyangslove** [comment]
请问你的问题解决了么？
