### ISSUE TITLE
build报错：mirror.android.os.storage.IStorageManager 未找到

### ISSUE THREAD

**Issue by mingio** [asLody/VirtualApp#370]
貌似兼容android8的，确实找不到这个类
    private static RefStaticMethod<IInterface> getInterfaceMethod() {
         if (BuildCompat.isOreo()) {
            return IStorageManager.Stub.asInterface;  //此处报错
        } else {
            return IMountService.Stub.asInterface;
        }
    }

**Comment by asLody** [comment]
Fixed.
