### ISSUE TITLE
双开QQ接受的文件不能用其他应用打开

### ISSUE THREAD

**Issue by hanyuejian** [asLody/VirtualApp#38]
双开QQ接受的文件不能用其他应用打开

**Comment by cddjr** [comment]
这个问题由两个原因产生
1、VA对于查看文件的意图，默认会修改为安装APK
2、因为VA里面的app与外界隔离，所以如果该文件关联的应用不在VA里面，则无法打开

问题1比较好处理，问题2得看你的需求，如果是想完全隔离，那么只需要修复问题1即可
