### ISSUE TITLE
华为mate8/P9 出现微信用QQ号邮箱登录的界面输入密码，输入法无法弹起的问题

### ISSUE THREAD

**Issue by mflk007** [asLody/VirtualApp#391]
华为mate8/P9 出现微信用QQ号邮箱登录的界面,点击输入密码 输入法无法弹起的问题

机型：华为mate8/P9
微信版本：6.5.16
系统：EMUI 5.0 /Android 7.0

**Comment by asLody** [comment]
Fixed.
