### ISSUE TITLE
无法打开微信语音和视频聊天界面

### ISSUE THREAD

**Issue by Damie2** [asLody/VirtualApp#392]
: Failed to find provider info for com.tencent.mm.coolassist.debugprovider
                                                   
                                                   --------- beginning of /dev/log/main
10-23 17:21:47.162 14280-14280/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtControlProviderAccountSync" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
10-23 17:21:47.162 14280-14280/? W/System.err: 	... 18 more
10-23 17:21:47.162 14280-14280/? W/System.err: java.lang.RuntimeException: Unable to get provider com.tencent.mm.plugin.gwallet.GWalletQueryProvider: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.gwallet.GWalletQueryProvider" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.162 14280-14280/? W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
10-23 17:21:47.162 14280-14280/? W/System.err:     at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:55)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:452)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:311)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-23 17:21:47.162 14280-14280/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.gwallet.GWalletQueryProvider" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
10-23 17:21:47.162 14280-14280/? W/System.err: 	... 18 more
10-23 17:21:47.162 14280-14280/? W/System.err: java.lang.RuntimeException: Unable to get provider com.tencent.mm.plugin.ext.provider.ExtControlProviderNearBy: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtControlProviderNearBy" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.162 14280-14280/? W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
10-23 17:21:47.162 14280-14280/? W/System.err:     at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:55)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:452)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:311)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-23 17:21:47.162 14280-14280/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtControlProviderNearBy" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
10-23 17:21:47.162 14280-14280/? W/System.err: 	... 18 more
10-23 17:21:47.162 14280-14280/? W/System.err: java.lang.RuntimeException: Unable to get provider com.tencent.mm.plugin.ext.provider.ExtControlProviderSNS: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtControlProviderSNS" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.162 14280-14280/? W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
10-23 17:21:47.162 14280-14280/? W/System.err:     at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:55)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:452)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:311)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-23 17:21:47.162 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-23 17:21:47.162 14280-14280/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-23 17:21:47.162 14280-14280/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtControlProviderSNS" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.162 14280-14280/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-23 17:21:47.162 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-23 17:21:47.162 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
10-23 17:21:47.162 14280-14280/? W/System.err: 	... 18 more
10-23 17:21:47.162 14280-14280/? W/System.err: java.lang.RuntimeException: Unable to get provider com.tencent.mm.plugin.base.stub.MMPluginProvider: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.base.stub.MMPluginProvider" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.172 14280-14280/? W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
10-23 17:21:47.172 14280-14280/? W/System.err:     at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:55)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:452)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:311)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-23 17:21:47.172 14280-14280/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-23 17:21:47.172 14280-14280/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-23 17:21:47.172 14280-14280/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.base.stub.MMPluginProvider" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.172 14280-14280/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
10-23 17:21:47.172 14280-14280/? W/System.err: 	... 18 more
10-23 17:21:47.172 14280-14280/? W/System.err: java.lang.RuntimeException: Unable to get provider com.tencent.mm.plugin.ext.provider.ExtContentProviderBase: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtContentProviderBase" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.172 14280-14280/? W/System.err:     at mirror.RefMethod.call(RefMethod.java:63)
10-23 17:21:47.172 14280-14280/? W/System.err:     at mirror.android.app.ActivityThread.installProvider(ActivityThread.java:55)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.installContentProviders(VClientImpl.java:452)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:311)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-23 17:21:47.172 14280-14280/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-23 17:21:47.172 14280-14280/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-23 17:21:47.172 14280-14280/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-23 17:21:47.172 14280-14280/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.ext.provider.ExtContentProviderBase" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tencent.mm-1.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualapp/virtual/data/app/com.tencent.mm/lib, /vendor/lib, /system/lib]]
10-23 17:21:47.172 14280-14280/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-23 17:21:47.172 14280-14280/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-23 17:21:47.172 14280-14280/? W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
10-23 17:21:47.172 14280-14280/? W/System.err: 	... 18 more
10-23 17:21:47.172 14280-14280/? D/HCallbackStub: HCallback has bad, other callback = com.tencent.mm.splash.g@42989958

**Comment by wangzhanxian** [comment]
我的也是，红米note3无法打开微信语音界面，应该是jni的问题

**Comment by asLody** [comment]
Fixed
