### ISSUE TITLE
关于VA的一个遗憾：缺乏对GMS支持

### ISSUE THREAD

**Issue by wanjin23** [asLody/VirtualApp#43]
细读作者代码，思路清晰，代码质量非常高，但有GMS服务的APP目前尚无法工作。目前的VA就像一个盖世武功高手，待练好降龙十八掌（GMS）才可以扬名于江湖(国际市场)。望作者加油～～

**Comment by gforetell** [comment]
你把他搞定，不就不缺了吗

**Comment by asLody** [comment]
已支持Gms。
