### ISSUE TITLE
facebook crash on Android L

### ISSUE THREAD

**Issue by lynn-long** [asLody/VirtualApp#430]
hey, all!
it's crash while i tried to double open facebook , this is the log
and, dual open facebook is perfect on android M
thank you very much!
********** Crash dump: **********
Build fingerprint: 'Xiaomi/lithium/lithium:7.0/NRD90M/7.12.7:user/release-keys'
pid: 21679, tid: 21711, name: EnsureDelegate  >>> com.facebook.katana <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Stack frame #00 pc 000187b8  /system/lib/libc.so (strlen+71)
Stack frame #01 pc 000077fb  /data/app/io.virtual-2/lib/arm/libva-native.so
Stack frame #02 pc 000076a9  /data/app/io.virtual-2/lib/arm/libva-native.so (_Z21match_redirected_pathPKc+32)
Stack frame #03 pc 0000867f  /data/app/io.virtual-2/lib/arm/libva-native.so (new_do_dlopen_V24+18)
Stack frame #04 pc 00002bed  /system/bin/linker (__dl__ZL10dlopen_extPKciPK17android_dlextinfoPv+28)
Stack frame #05 pc 00000f43  /data/data/io.virtual/virtual/data/user/0/com.facebook.katana/lib-xzs/libfbsystrace.so
Stack frame #06 pc 00239dd5  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectP8_jstringPS9_+1844)
Stack frame #07 pc 00003167  /system/lib/libopenjdkjvm.so (JVM_NativeLoad+178)
Stack frame #08 pc 005df18d  /system/framework/arm/boot.oat (offset 0x56e000) (java.lang.Runtime.nativeLoad+144)
Stack frame #09 pc 000a9141  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
Stack frame #10 pc 004032f5  /system/lib/libart.so (art_quick_invoke_static_stub+228)
Stack frame #11 pc 000b03ff  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
Stack frame #12 pc 0031351d  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+56)
Stack frame #13 pc 003148af  /system/lib/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_j+766)
Stack frame #14 pc 002bb9b9  /system/lib/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+40)
Stack frame #15 pc 00604fd9  /system/framework/arm/boot.oat (offset 0x56e000) (java.lang.reflect.Method.invoke+116)
Stack frame #16 pc 000094a7  /dev/ashmem/dalvik-jit-code-cache (deleted)

**Comment by asLody** [comment]
please update your code.
