### ISSUE TITLE
可以通过virtualapp链接非公开库吗？

### ISSUE THREAD

**Issue by scucsxn** [asLody/VirtualApp#446]
https://developer.android.com/about/versions/nougat/android-7.0-changes.html?hl=zh-cn#ndk

7.0禁止链接非公开库

比如想在7.0上想使用imageHandle = dlopen("/system/lib/libmedia.so", RTLD_GLOBAL | RTLD_NOW);就没有办法了吗

**Comment by addhaloka** [comment]
https://github.com/avs333/Nougat_dlfunctions

**Comment by scucsxn** [comment]
看了一下貌似只能对这个libutils.so使用，对libmedia.so可以用吗

**Comment by scucsxn** [comment]
01-18 16:20:01.572 18022-18022/io.virtualhook W/linker: library "/system/lib/libmedia.so" ("/system/lib/libmedia.so") needed or dlopened by "/data/app/io.virtualhook-2/lib/arm/libva++.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-18 16:20:01.612 18022-18022/io.virtualhook E/linker: library "libavenhancements.so" ("/system/vendor/lib/libavenhancements.so") needed or dlopened by "/system/lib/libmedia.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/io.virtualhook-2/lib/arm:/system/fake-libs:/data/app/io.virtualhook-2/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/io.virtualhook"]
01-18 16:20:01.771 18086-18086/io.virtualhook:x W/linker: library "/system/lib/libmedia.so" ("/system/lib/libmedia.so") needed or dlopened by "/data/app/io.virtualhook-2/lib/arm/libva++.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-18 16:20:01.812 18086-18086/io.virtualhook:x E/linker: library "libavenhancements.so" ("/system/vendor/lib/libavenhancements.so") needed or dlopened by "/system/lib/libmedia.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/io.virtualhook-2/lib/arm:/system/fake-libs:/data/app/io.virtualhook-2/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/io.virtualhook"]

**Comment by addhaloka** [comment]
不明白为何有这种需求, 上面那个不行吗?试试这个
