### ISSUE TITLE
reopen an opened app in VA will create another thumbnail in Android‘s recent-app-list window

### ISSUE THREAD

**Issue by prife** [asLody/VirtualApp#47]
two main issues:
- reopen an opened app in VA is very slow, while in navite Android it is fast.
- will create another thumbnail in Android‘s recent-app-list window.
![dup](https://cloud.githubusercontent.com/assets/1572684/17374830/faa47032-59e0-11e6-83db-cab40a0e0aa9.jpg)

**Comment by asLody** [comment]
Invalid issue.
自己看DEMO的代码，启动一个app前先会杀死它。
