### ISSUE TITLE
VA might not work on Android P(Android 9)

### ISSUE THREAD

**Issue by mustime** [asLody/VirtualApp#470]
FYI: https://developer.android.com/preview/restrictions-non-sdk-interfaces.html

Android P introduces new restrictions on the use of non-SDK interfaces, whether directly, via reflection, or via JNI. These restrictions are applied whenever an app references a non-SDK interface or attempts to obtain its handle using reflection or JNI.

**Comment by zhangyulong882** [comment]
已经跪了，所有插件技术都跪了

**Comment by zhangyulong882** [comment]
已经跪了，所有的插件框架都跪了

**Comment by asLody** [comment]
Don't worry about it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MissGongYi** [comment]
The author provides the commercial version of this library, which supports Android 9。花点钱，下次碰到这种情况花点钱
