### ISSUE TITLE
关于VActivityManager.get().startActivity

### ISSUE THREAD

**Issue by AllenMeex** [asLody/VirtualApp#473]
宿主调起插件app貌似只能用 VActivityManager.get().startActivity(intent, {userId}); 方法，为何没有startActivityForResult()方法呢？
请问宿主如何以forResult方式调起内部app的Activity~

**Comment by asLody** [comment]
宿主和插件app的activity不在同一个task，所以没法回调onActivityResult

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AllenMeex** [comment]
了解了，多谢作者~
