### ISSUE TITLE
这个可以实现插件宿主之间的通信么

### ISSUE THREAD

**Issue by cjqq354139968** [asLody/VirtualApp#475]
现在想使用插件调用宿主的一些方法，从而能达到宿主和多apk页面的逻辑以及UI实现。

**Comment by liyic** [comment]
应该可以，不过得自己看源码实现了。

**Comment by bebetter1030** [comment]
BroadcastReceiver

**Comment by THROFHR** [comment]
最后这个问题有什么解决方法吗？

**Comment by DoveBarnett** [comment]
> BroadcastReceiver

这个可以吗？我怎么试了在里面的APP发送广播给沙箱，沙箱并不能接收到广播呢？
