### ISSUE TITLE
oppo手机运行荒野行动游戏异常

### ISSUE THREAD

**Issue by haiyang0932** [asLody/VirtualApp#501]
现象：oppo手机运行官方渠道包的荒野行动游戏，在游戏界面的出现与消失时 通过virtualCore.setComponentDelegate设置的delegate 生命周期方法未得到回调

测试机型：oppo r9m、oppo r11

**Comment by 247321453** [comment]
请用registerActivityLifecycleCallbacks

**Comment by haiyang0932** [comment]
已解决
