### ISSUE TITLE
not use google play account to sign in

### ISSUE THREAD

**Issue by marwar6** [asLody/VirtualApp#51]
virtualapp is great ! 
why not use google play account to sign in games ?

**Comment by gforetell** [comment]
why? you writed my question here! im sad!

**Comment by asLody** [comment]
Hello,
Now you can use VirtualApp sign in the Google account!

**Comment by marwar6** [comment]
Hi @asLody  
It 's good, but not perfect. if you use google play account login game will crash . 
eg:
https://play.google.com/store/apps/details?id=com.supercell.clashofclans
https://play.google.com/store/apps/details?id=com.supercell.clashroyale
