### ISSUE TITLE
请教一下，如何通过am与虚拟化出的app进行交互

### ISSUE THREAD

**Issue by casazaft** [asLody/VirtualApp#71]
对于原生装到系统上的app进程，通过am start -n package/activity 的命令可以启动对应activity，传递参数，但是对于virtual的app，am的命令只会发送给系统原生对应的app进程，不知道要如何才能交互？

**Comment by RandeeCao** [comment]
这个应该实现不了吧 AM能够启动的应用 只能是在系统里面安装过切存在的

**Comment by asLody** [comment]
不能通过外部启动VA内部的app.
但是稍加扩展就可以：
你可以注册一个代理Activity，然后通过am命令启动到这个代理Activity后，再根据传递的参数启动到真正的Activity.
