### ISSUE TITLE
老的代码可以打开facebook，但是用账号一直登陆不上去

### ISSUE THREAD

**Issue by renqingyou** [asLody/VirtualApp#72]
老的代码可以打开facebook，但是用facebook账号一直登陆不上去。

**Comment by renqingyou** [comment]
在老的代码基础上，发现4.1的系统可以打开并登陆facebook, 5.0以后的可以打开，但是登陆不上

**Comment by renqingyou** [comment]
报错如下
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.facebook.appmanager
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 E/art: invalid stream - problem with parameter iterator in /data/data/io.virtualapp/app_VApps/com.facebook.katana/dex/prog-581aa23ce24a06358859563940b2489dce5555bc.dex for method void com.facebook.oxygen.preloads.integration.dogfooding.AuthListener.a(com.facebook.oxygen.preloads.integration.dogfooding.AuthListener, android.content.Intent)
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err:     at com.facebook.oxygen.preloads.integration.dogfooding.AuthListener.a()
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err:     at com.facebook.common.executors.DefaultConstrainedListeningExecutorService$Worker.run(:60547)
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err:     at com.facebook.common.executors.DefaultConstrainedListeningExecutorService$Worker.run(:60547)

**Comment by piersguo** [comment]
问下你这边用能登录Facebook了吗，我用最新VA试过，第一次登录facebook会闪退，但是闪退后再次登录就成功了。目前不清楚为何会导致闪退，请问你这边研究有什么进展吗
