### ISSUE TITLE
请问一下，VA和DroidPlugin的实现机制大致是否相同么？

### ISSUE THREAD

**Issue by motcwang** [asLody/VirtualApp#75]
VA和DroidPlugin的区别和优缺点有那些呢？

**Comment by littleblackblack** [comment]
一样一样的。之前DP没有elf
hook。va做了简单的文件重定向。不论native层还是java层的运行环境的构建都还不完善，加载的app有逃逸的情况。

2016-08-26 8:20 GMT+08:00 Chao Wang <notifications@github.com>:

**Comment by littleblackblack** [comment]
一样一样的。之前DP没有elf hook。va做了简单的文件重定向。不论native层还是java层的运行环境的构建都还不完善，
加载的app有逃逸的情况。

2016-08-26 8:20 GMT+08:00 Chao Wang <notifications@github.com>:
