### ISSUE TITLE
部分应用未适配（白屏，黑屏，ANR）

### ISSUE THREAD

**Issue by duqian291902259** [asLody/VirtualApp#8]
加入应用，打开时先白屏再黑屏，无响应。。。Samsung SM-G5309W,android 4.4。
Could not find method android.app.Application.dispatchOnProvideAssistData, referenced from method io.virtualapp.VApp.access$super

**Comment by dodola** [comment]
@duqian291902259 打开的是什么应用？

**Comment by 247321453** [comment]
我猜有jni层的io操作，或者是Application的onCreate启动了服务。

**Comment by asLody** [comment]
能描述得更详细一些吗？
所有应用都这样，还是部分应用？
有没有日志？

**Comment by duqian291902259** [comment]
只是部分应用像360手机助手，爱奇艺视频进不了，有些应用进入后某个activity会闪退（实际单独运行不会），日志容我有空导出。
