### ISSUE TITLE
8月9号的版本在Android 5.0机器上能打开Facebook和Messenger，但是登陆不了？

### ISSUE THREAD

**Issue by yubingxing** [asLody/VirtualApp#81]
8月9号的版本在Android4.4的机器上面能正常打开和登陆Facebook和Messenger，但是在Android 5.0以上机器上面无法登陆成功，具体是什么问题？最新的版本是不支持Facebook和Messenger的。

**Comment by renqingyou** [comment]
我也碰到这个问题，报错如下：
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.facebook.appmanager
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 E/art: invalid stream - problem with parameter iterator in /data/data/io.virtualapp/app_VApps/com.facebook.katana/dex/prog-581aa23ce24a06358859563940b2489dce5555bc.dex for method void com.facebook.oxygen.preloads.integration.dogfooding.AuthListener.a(com.facebook.oxygen.preloads.integration.dogfooding.AuthListener, android.content.Intent)
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err:     at com.facebook.oxygen.preloads.integration.dogfooding.AuthListener.a()
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err:     at com.facebook.common.executors.DefaultConstrainedListeningExecutorService$Worker.run(:60547)
08-30 09:25:56.912 30640-30826/io.virtualapp:p9 W/System.err:     at com.facebook.common.executors.DefaultConstrainedListeningExecutorService$Worker.run(:60547)
