### ISSUE TITLE
launcher mode 为 singleTask好像也有问题

### ISSUE THREAD

**Issue by renqingyou** [asLody/VirtualApp#97]
在Google play主界面点击排行榜，进入排行榜界面，点击左上角 返回按钮，回退到Google play主界面，

再按返回键，会直接回退到系统launcher界面，没有回退到VirtualApp主页面。

PS: 回退到的google play界面实际上已经是新启动的Activity,非之前启动的StubAcitivyt

**Comment by tianfengjingjing** [comment]
singleInstance的试过没

**Comment by asLody** [comment]
Fixed.
